name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: |
          cd app
          ./gradlew build

      - name: Run Checkstyle
        run: |
          cd app
          ./gradlew checkstyleMain checkstyleTest

      - name: Run tests with coverage
        run: |
          cd app
          ./gradlew test jacocoTestReport

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: app/
          args: >
            -Dsonar.organization=julia-tretyak
            -Dsonar.projectKey=julia-tretyak_qa-auto-engineer-java-project-61
            -Dsonar.sources=src/main/java
            -Dsonar.java.binaries=build/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/html/jacocoTestReport.xml
            -Dsonar.gradle.skipCompile=true
